include:
  - board: seeeduino_xiao_ble
    shield: totem_tp_left
  - board: seeeduino_xiao_ble
    shield: totem_tp_right
  - board: seeeduino_xiao_ble
    shield: totem_tp_dongle prospector_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: seeeduino_xiao_ble
    shield: settings_reset
